import React from "react";

const privacyPolicy = [
  { type: "title", content: "Privacy Policy" },
  { type: "paragraph", content: "Last updated: November 05, 2024" },
  {
    type: "paragraph",
    content:
      "This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.",
  },
  {
    type: "paragraph",
    content:
      "We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.",
  },

  { type: "title", content: "Interpretation and Definitions" },
  { type: "title", content: "Interpretation" },
  {
    type: "paragraph",
    content:
      "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
  },

  { type: "title", content: "Definitions" },
  { type: "paragraph", content: "For the purposes of this Privacy Policy:" },
  {
    type: "list",
    content: [
      "Account means a unique account created for You to access our Service or parts of our Service.",
      "Affiliate means an entity that controls, is controlled by or is under common control with a party.",
      "Company (referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to Blue Square, 7, Sumbo Jibowu Street, S.W. Ikoyi, Lagos.",
      "Cookies are small files placed on Your device by a website, containing details of Your browsing history.",
      "Country refers to Nigeria.",
      "Device means any device that can access the Service such as a computer, cellphone, or tablet.",
      "Personal Data is any information that relates to an identified or identifiable individual.",
      "Service refers to the Website.",
      "Service Provider means any natural or legal person who processes the data on behalf of the Company.",
      "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.",
      "Website refers to Blue Square, accessible from https://www.bluesquareng.com/",
      "You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
    ],
  },

  { type: "title", content: "Collecting and Using Your Personal Data" },
  { type: "title", content: "Types of Data Collected" },

  { type: "title", content: "Personal Data" },
  {
    type: "paragraph",
    content:
      "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
  },
  {
    type: "list",
    content: [
      "Email address",
      "First name and last name",
      "Phone number",
      "Address, State, Province, ZIP/Postal code, City",
      "Usage Data",
    ],
  },
  { type: "title", content: "Usage Data" },
  {
    type: "paragraph",
    content: "Usage Data is collected automatically when using the Service.",
  },
  {
    type: "paragraph",
    content:
      "Usage Data may include information such as Your Device's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
  },

  { type: "title", content: "Tracking Technologies and Cookies" },
  {
    type: "paragraph",
    content:
      "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information.",
  },
  {
    type: "list",
    content: [
      "Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.",
      "Flash Cookies. Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service.",
      "Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages or opened an email and for other related website statistics.",
    ],
  },

  { type: "title", content: "Use of Your Personal Data" },
  {
    type: "paragraph",
    content: "The Company may use Personal Data for the following purposes:",
  },
  {
    type: "list",
    content: [
      "To provide and maintain our Service, including to monitor the usage of our Service.",
      "To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.",
      "For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.",
      "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.",
      "To provide You with news, special offers and general information about other goods, services and events.",
      "To manage Your requests: To attend and manage Your requests to Us.",
    ],
  },

  { type: "title", content: "Retention of Your Personal Data" },
  {
    type: "paragraph",
    content:
      "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.",
  },
  {
    type: "paragraph",
    content:
      "The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.",
  },

  { type: "title", content: "Transfer of Your Personal Data" },
  {
    type: "paragraph",
    content:
      "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.",
  },
  {
    type: "paragraph",
    content:
      "Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.",
  },
  {
    type: "paragraph",
    content:
      "The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.",
  },

  { type: "title", content: "Delete Your Personal Data" },
  {
    type: "paragraph",
    content:
      "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.",
  },
  {
    type: "paragraph",
    content:
      "Our Service may give You the ability to delete certain information about You from within the Service.",
  },
  {
    type: "paragraph",
    content:
      "You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.",
  },
  {
    type: "paragraph",
    content:
      "Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.",
  },

  { type: "title", content: "Disclosure of Your Personal Data" },
  {
    type: "list",
    content: [
      "Business Transactions. If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.",
      "Law enforcement. Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).",
      "Other legal requirements. The Company may disclose Your Personal Data in the good faith belief that such action is necessary to: comply with a legal obligation, protect and defend the rights or property of the Company, prevent or investigate possible wrongdoing in connection with the Service, protect the personal safety of Users of the Service or the public, and protect against legal liability.",
    ],
  },

  { type: "title", content: "Security of Your Personal Data" },
  {
    type: "paragraph",
    content:
      "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.",
  },

  { type: "title", content: "Children's Privacy" },
  {
    type: "paragraph",
    content:
      "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.",
  },
  {
    type: "paragraph",
    content:
      "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.",
  },

  { type: "title", content: "Links to Other Websites" },
  {
    type: "paragraph",
    content:
      "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.",
  },
  {
    type: "paragraph",
    content:
      "We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.",
  },

  { type: "title", content: "Changes to this Privacy Policy" },
  {
    type: "paragraph",
    content:
      "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.",
  },
  {
    type: "paragraph",
    content:
      "We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the 'Last updated' date at the top of this Privacy Policy.",
  },
  {
    type: "paragraph",
    content:
      "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.",
  },

  { type: "title", content: "Contact Us" },
  {
    type: "paragraph",
    content:
      "If you have any questions about this Privacy Policy, You can contact us:",
  },
  { type: "paragraph", content: "By email: marketing@bluesquareng.com" },
];

function PrivacyPolicy() {
  return (
    <div className="max-w-7xl mx-auto p-4 space-y-6 text-white pt-20">
      {privacyPolicy.map((section, index) => {
        switch (section.type) {
          case "title":
            return (
              <h2 key={index} className="text-2xl font-bold text-gray-50 mt-8">
                {section.content}
              </h2>
            );
          case "paragraph":
            return (
              <p key={index} className="text-gray-300 leading-relaxed">
                {section.content}
              </p>
            );
          case "list":
            return (
              <ul
                key={index}
                className="list-disc list-inside space-y-2 text-gray-300"
              >
                {section.content.map((item, i) => (
                  <li key={i} className="leading-relaxed">
                    {item}
                  </li>
                ))}
              </ul>
            );
          default:
            return null;
        }
      })}
    </div>
  );
}

export default PrivacyPolicy;
